# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fb7e3409250d7259e3da3ee5809124e481a30e877c8268bf0b3433d2b4dc142899996f79e31787259528ed7be191d1f44427fa62798f0317830bf6ca35bb0e3b

test:
  secret_key_base: 88c9a4e23279df8e0165d6cf2b28374b20f49f8fcad129de62316718bb87cff3fcc7f36eaa470b73a5be13b24f431542a1fed73ee9e5df95ad8bda5077b10167

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
